os: Visual Studio 2015

version: 0.4.0-rc2-{build}
configuration: Release
cache: C:\Users\appveyor\.dnx\packages

nuget:
  disable_publish_on_pr: true
  
pull_requests:
  do_not_increment_build_number: true

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet
  
build:
  verbosity: minimal

test: off
